[package]
version = "0.1.2"
name = "hallr"
edition = "2021"
readme = "README.md"
description = "An experimental Blender addon"
repository = "https://github.com/eadf/hallr"
license = "AGPL-3.0-or-later"
authors = ["eadf"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "1.0.50"
linestring = "0.10.2"
centerline = { version="0.8.0", features = ["glam"]}
vector-traits = { version = "0.2.0", features = ["glam"] }
krakel = {version = "0.2.0", features = ["glam"]}
hronn = { version = "0.1.0", features = ["glam"]}
ahash = "0.8.6"
smallvec = "1.11.1"
boostvoronoi = { version = "0.11.0" }
rayon = "1.8.0"
itertools = "0.11.0"
vob = "3.0.3"
earcutr = "0.4.3"
