[package]
version = "0.1.3"
name = "hallr"
edition = "2024"
readme = "README.md"
description = "An experimental Blender addon"
repository = "https://github.com/eadf/hallr"
license = "AGPL-3.0-or-later"
authors = ["eadf"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#vector-traits = { version = "0.3.4", features = ["glam"] }
#vector-traits = { path = "../vector-traits", features = ["glam"] }
vector-traits = {git = "https://codeberg.org/eadf/vector_traits_rs.git", features = ["glam"]}
#linestring = "0.13.0"
#linestring = { path="../linestring.rs"}
linestring = {git = "https://codeberg.org/eadf/linestring_rs.git"}
#centerline = { version="0.11.0", features = ["glam"]}
#centerline = { path="../centerline.rs", features = ["glam"]}
centerline = {git = "https://codeberg.org/eadf/centerline_rs.git", features = ["glam"]}
#krakel = {version = "0.2.3", features = ["vector-traits", "glam"]}
#krakel = {path = "../krakel", features = ["vector-traits", "glam"]}
krakel = {git = "https://codeberg.org/eadf/krakel_rs.git"}
#hronn = { version = "0.4.1", features = ["glam"]}
#hronn = { path = "../hronn.rs", features = ["glam"]}
hronn = { git = "https://codeberg.org/eadf/hronn_rs.git", features = ["glam"]}
boostvoronoi = { version = "0.11.1" }
thiserror = "2.0.12"
ahash = "0.8.11"
smallvec = "1.14.0"
rayon = "1.10.0"
itertools = "0.14.0"
vob = "3.0.4"
earcutr = "0.4.3"
ilattice = { version="0.4.0", default-features = false, features = ["glam"]}
fast-surface-nets = "0.2.1"
baby_shark = "0.3.3"

[dev-dependencies]
rand = "0.9.0"
criterion = "0.5.1"

[features]
glam-core-simd  = ["vector-traits/glam-core-simd"]
glam-fast-math = ["vector-traits/glam-fast-math"]
display_sdf_chunks = []

[profile.release]
lto = true
