[package]
version = "0.1.13"
name = "hallr"
edition = "2024"
readme = "README.md"
description = "An experimental Blender addon"
repository = "https://github.com/eadf/hallr"
license = "AGPL-3.0-or-later"
authors = ["eadf"]
rust-version = "1.85.1"
keywords = ["blender", "voronoi", "lsystems", "geometry"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vector-traits = "0.4.0"
#vector-traits = { path = "../vector-traits" }
#vector-traits = {git = "https://codeberg.org/eadf/vector_traits_rs.git"}
linestring = "0.14.0"
#linestring = { path="../linestring.rs"}
#linestring = {git = "https://codeberg.org/eadf/linestring_rs.git"}
centerline = { version="0.12.1", features = ["glam"]}
#centerline = { path="../centerline.rs", features = ["glam"]}
#centerline = {git = "https://codeberg.org/eadf/centerline_rs.git", features = ["glam"]}
krakel = {version = "0.3.1", features = ["vector-traits", "glam"]}
#krakel = {path = "../krakel", features = ["vector-traits", "glam"]}
#krakel = {git = "https://codeberg.org/eadf/krakel_rs.git"}
hronn = { version = "0.5.4", features = ["glam"]}
#hronn = { path = "../hronn.rs", features = ["glam"]}
#hronn = { git = "https://codeberg.org/eadf/hronn_rs.git", features = ["glam"]}
boostvoronoi = { version = "0.11.1" }
thiserror = "2.0.12"
ahash = "0.8.11"
smallvec = "1.15.0"
rayon = "1.10.0"
itertools = "0.14.0"
vob = "3.0.4"
earcutr = "0.4.3"
ilattice = { version="0.4.0", default-features = false, features = ["glam"]}
fast-surface-nets = "0.2.1"
baby_shark = "0.3.8"
logos = "0.15"
ryu = { version="1.0.20", optional=true }
saft = { version="0.34.1", features = ["with_rayon"]}
macaw = { version="^0.19"} # macaw must be the same version that saft uses

[dev-dependencies]
rand = "0.9.0"
# criterion = "0.5.1"

[features]
generate_test_case_from_input = ["dep:ryu"]
glam-core-simd  = ["vector-traits/glam-core-simd"]
glam-fast-math = ["vector-traits/glam-fast-math"]
display_sdf_chunks = []

[profile.release]
lto = true
