[package]
name = "hallr"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "An experimental Blender addon"
repository = "https://github.com/eadf/hallr"
license = "AGPL-3.0-or-later"
authors = ["eadf"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thiserror = "1.0.50"
linestring = "0.10.1"
vector-traits = { version = "0.2.0", features = ["glam"] }
krakel = {version = "0.2.0", features = ["glam"]}
hronn = { version = "0.1.0", features = ["glam"]}

[dev-dependencies]
rand = "0.8.5"
