[package]
version = "0.1.2"
name = "hallr"
edition = "2021"
readme = "README.md"
description = "An experimental Blender addon"
repository = "https://github.com/eadf/hallr"
license = "AGPL-3.0-or-later"
authors = ["eadf"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vector-traits = { version = "0.3.1", features = ["glam"] }
#vector-traits = { path = "../vector-traits", features = ["glam"] }
linestring = "0.11.0"
#linestring = { path="../linestring.rs"}
centerline = { version="0.9.0", features = ["glam"]}
#centerline = { path="../centerline.rs"}
krakel = {version = "0.2.0", features = ["glam"]}
hronn = { version = "0.2.0", features = ["glam"]}
#hronn = { path = "../hronn.rs", features = ["glam"]}
boostvoronoi = { version = "0.11.0" }
thiserror = "1.0.50"
ahash = "0.8.6"
smallvec = "1.11.2"
rayon = "1.8.0"
itertools = "0.11.0"
vob = "3.0.3"
earcutr = "0.4.3"

[dev-dependencies]
rand = "0.8.5"
criterion = "0.5.1"

[profile.release]
lto = true
