name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Update Rust
        run: rustup update

      - name: Run Clippy
        run: cargo clippy --all

      - name: Run tests
        run: cargo test --all

      - name: Run build script
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            python build_script.py
          else
            python3 build_script.py
          fi
        shell: bash

